language: python

python:
  - "3.6"

install:
  - pip install numpy
  - pip install coveralls

before_script:
  - cd neural-network

script:
  - python -m unittest discover
  - coverage run -m unittest discover

after_success:
  - coveralls 

